### ISSUE TITLE
Errors on unrecognized cops

### ISSUE THREAD

**Issue by jcoyne** [Shopify/erb-lint#163]
When running rubocop-rspec and rubocop-rails I see this error when running erb-lint:
```
RuboCop::ValidationError: unrecognized cop RSpec/AnyInstance found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/ContextWording found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/DescribeClass found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/ExampleLength found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/ExpectInHook found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/FilePath found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/InstanceVariable found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/IteratedExpectation found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/MessageChain found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/MessageSpies found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/NamedSubject found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/NestedGroups found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/PredicateMatcher found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/ScatteredLet found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/SubjectStub found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop RSpec/VerifiedDoubles found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/ActiveRecordAliases found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/ApplicationJob found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/Blank found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/EnvironmentComparison found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/FilePath found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/HasManyOrHasOneDependent found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/HelperInstanceVariable found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/LexicallyScopedActionFilter found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/OutputSafety found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/Present found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/RakeEnvironment found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/SkipsModelValidations found in .erblint-rubocop20200429-12840-848tz0, unrecognized cop Rails/TimeZone found in .erblint-rubocop20200429-12840-848tz0

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/rubocop-0.82.0/lib/rubocop/config_validator.rb:99:in `alert_about_unrecognized_cops'

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/rubocop-0.82.0/lib/rubocop/config_validator.rb:40:in `validate'

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/rubocop-0.82.0/lib/rubocop/config.rb:44:in `check'

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/rubocop-0.82.0/lib/rubocop/config.rb:37:in `create'

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/rubocop-0.82.0/lib/rubocop/config_loader.rb:54:in `load_file'

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/erb_lint-0.0.32/lib/erb_lint/linters/rubocop.rb:132:in `block in config_from_hash'

/home/travis/build/sul-dlss/argo/vendor/bundle/ruby/2.6.0/gems/erb_lint-0.0.32/lib/erb_lint/linters/rubocop.rb:95:in `block in tempfile_from'
```

**Comment by tsrivishnu** [comment]
I had the same issue: 

```
RuboCop::ValidationError: unrecognized cop GitlabSecurity/JsonSerialization found in .erblint-rubocop20200804-8-1b5pd4o, unrecognized cop GitlabSecurity/PublicSend found in .erblint-rubocop20200804-8-1b5pd4o, unrecognized cop GitlabSecurity/SqlInjection found in .erblint-rubocop20200804-8-1b5pd4o
```

Also fixed by adding the following to `.rubocop_todo.yml` which was already present in `.rubocop.yml`
```
require:
  - rubocop-gitlab-security
  - rubocop-rails
```

The issue could be because of `.rubocop.yml` having `inherit_from: .rubocop_todo.yml` in the top of the file.
