### ISSUE TITLE
erb_lint can't resolve configs from gems

### ISSUE THREAD

**Issue by brendo** [Shopify/erb-lint#184]
Our project is attempting to migrate to use "gem" based Rubocop configs to try and smooth out the bumps when external dependencies change.

At the moment, our `rubocop.yml` file has the following lines:

```yml
inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml
```

This is problematic as we get into scenarios where that file will update but our version of Rubocop doesn't support the new lint rules and ERB Lint doesn't support those rules either. 

To solve we're attempting to migrate to the "gem" approach as described in https://shopify.github.io/ruby-style-guide/:

```
inherit_from:
  rubocop-shopify: rubocop.yml
```

This results in a crash when running erb_lint:

```
$ bundle exec erblint --lint-all
Linting 943 files with 14 linters...

TypeError: no implicit conversion of Array into String
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/file_loader.rb:25:in `expand_path'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/file_loader.rb:25:in `read_content'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/file_loader.rb:14:in `yaml'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:182:in `block in base_configs'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:178:in `map'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:178:in `base_configs'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:168:in `resolve_inheritance'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:160:in `config_from_hash'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:182:in `block in base_configs'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:178:in `map'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:178:in `base_configs'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:168:in `resolve_inheritance'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:160:in `config_from_hash'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/linters/rubocop.rb:27:in `initialize'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/runner.rb:16:in `new'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/runner.rb:16:in `block in initialize'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/runner.rb:15:in `map'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/runner.rb:15:in `initialize'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/cli.rb:58:in `new'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/cli.rb:58:in `run'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/exe/erblint:9:in `<top (required)>'
/Users/brendanabbott/.gem/ruby/2.6.6/bin/erblint:23:in `load'
/Users/brendanabbott/.gem/ruby/2.6.6/bin/erblint:23:in `<top (required)>'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/brendanabbott/.gem/ruby/2.6.6/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/Users/brendanabbott/.gem/ruby/2.6.6/bin/bundle:23:in `load'
/Users/brendanabbott/.gem/ruby/2.6.6/bin/bundle:23:in `<main>'
```

With a pry session, I was able to see that erb_lint is choking on:

```
From: /Users/brendanabbott/.gem/ruby/2.6.6/gems/erb_lint-0.0.35/lib/erb_lint/file_loader.rb:28 ERBLint::FileLoader#read_content:

    24: def read_content(filename)
    25:   require 'pry'
    26:   binding.pry
    27: 
 => 28:   path = File.expand_path(filename, base_path)
    29:   File.read(path)
    30: end

[1] pry(#<ERBLint::FileLoader>)> filename
=> ["rubocop-shopify", "rubocop.yml"]
```

**Comment by brendo** [comment]
My fault. To use config from a gem you need to use `inherit_gem`, not `inherit_from`:

```yml
inherit_gem:
  rubocop-shopify: rubocop.yml
```

More ☕ needed 😓
