### ISSUE TITLE
Rails 6.1 - undefined method `delegate' for ERBLint::Reporter:Class

### ISSUE THREAD

**Issue by justinko** [Shopify/erb-lint#197]
Just upgraded to Rails 6.1 and am now getting this error:

```
/Users/jko/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/erb-lint-05596ea189ee/lib/erb_lint/reporter.rb:36:in `<class:Reporter>': undefined method `delegate' for ERBLint::Reporter:Class (NoMethodError)
```

Is `delegation` [now included](https://github.com/rails/rails/blob/6-1-stable/activesupport/lib/active_support/core_ext/module.rb#L10) from `module.rb`?

**Comment by haidangwa** [comment]
This bug was introduced in `erb_lint 0.0.36`. We've been runnning v0.0.35 of erb_lint and our CI pipeline failed today when it pulled down the new version.

**Comment by haidangwa** [comment]
```$ gem install erb_lint
Successfully installed tzinfo-2.0.4
Successfully installed zeitwerk-2.4.2
Successfully installed activesupport-6.1.0
Successfully installed crass-1.0.6
Successfully installed loofah-2.8.0
Successfully installed rails-html-sanitizer-1.3.0
Successfully installed rails-dom-testing-2.0.3
Successfully installed actionview-6.1.0
Successfully installed smart_properties-1.15.0
Building native extensions. This could take a while...
Successfully installed html_tokenizer-0.0.7
Successfully installed better_html-1.0.15
Successfully installed erb_lint-0.0.36
12 gems installed
$ erblint --lint-all --config .erb-lint.yml
/root/.chefdk/gem/ruby/2.7.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:36:in `<class:Reporter>': undefined method `delegate' for ERBLint::Reporter:Class (NoMethodError)
Did you mean?  DelegateClass
	from /root/.chefdk/gem/ruby/2.7.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:5:in `<module:ERBLint>'
	from /root/.chefdk/gem/ruby/2.7.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:4:in `<top (required)>'
	from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /root/.chefdk/gem/ruby/2.7.0/gems/erb_lint-0.0.36/lib/erb_lint.rb:16:in `<top (required)>'
	from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /root/.chefdk/gem/ruby/2.7.0/gems/erb_lint-0.0.36/lib/erb_lint/cli.rb:3:in `<top (required)>'
	from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /root/.chefdk/gem/ruby/2.7.0/gems/erb_lint-0.0.36/exe/erblint:6:in `<top (required)>'
	from /root/.chefdk/gem/ruby/2.7.0/bin/erblint:23:in `load'
	from /root/.chefdk/gem/ruby/2.7.0/bin/erblint:23:in `<main>'
```
