### ISSUE TITLE
Autocorrect fails with exception: undefined method `autocorrect' for #<ERBLint::Linters::ErbSafety

### ISSUE THREAD

**Issue by mattbrictson** [Shopify/erb-lint#263]
Autocorrect no longer works with `ErbSafety` enabled. This seems to be a regression introduced on 0.1.2.

With this simple `.erb-lint.yml`:

```yaml
---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
```

Run:

```
$ erblint --lint-all --autocorrect
```

Produces this error:

```
Exception occurred when processing: app/views/shared/_flash.html.erb
If this file cannot be processed by erb-lint, you can exclude it in your configuration file.
undefined method `autocorrect' for #<ERBLint::Linters::ErbSafety:0x00000001168f0c48 [...omitted for brevity...]>

        offense.linter.autocorrect(@processed_source, offense)
                      ^^^^^^^^^^^^
gems/erb_lint-0.1.3/lib/erb_lint/corrector.rb:15:in `block in corrections'
gems/erb_lint-0.1.3/lib/erb_lint/corrector.rb:14:in `map'
gems/erb_lint-0.1.3/lib/erb_lint/corrector.rb:14:in `corrections'
gems/erb_lint-0.1.3/lib/erb_lint/corrector.rb:20:in `corrector'
gems/erb_lint-0.1.3/lib/erb_lint/corrector.rb:10:in `initialize'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:148:in `new'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:148:in `correct'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:110:in `block in run_with_corrections'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:105:in `times'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:105:in `run_with_corrections'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:64:in `block in run'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:61:in `each'
gems/erb_lint-0.1.3/lib/erb_lint/cli.rb:61:in `run'
gems/erb_lint-0.1.3/exe/erblint:9:in `<top (required)>'
bin/erblint:29:in `load'
bin/erblint:29:in `<main>'
```

Expectation:

- `erblint` should skip linters that do not support autocorrect, rather than crashing with an exception
- Alternatively, there should be a way to explicitly skip linters that do not support autocorrect, like `--disable-linters erb_safety`

**Comment by etiennebarrie** [comment]
Can you try #264? That should fix it.
